### ISSUE TITLE
Error bij aftrappen ETL #2

### ISSUE THREAD

**Issue by jvlith** [NLHEALTHCARE/PYELT#10]
Hoi Hj,

dit is de reden waarom het script niet draait en wij dus geen mails krijgen.
Ik heb met dwh2_clinics user op shannon het bash script pull_and_run.sh gedraaid.

Vragen:
1) We kunnen maandag wel even kijken aangezien het volgens mij niet iets is waar ik meteen mee van doen heb gehad.
2) Voorstel om de mails ook te laten schieten als het failed. Ik heb nu het idee dat we alleen een mail krijgen als het script totaal heeft gerund (iig tot het einde).

Zie hieronder voor de foutmelding

START FROM SOURCE TO SOR                                    executed in 0.000 seconds (6.632 seconds since start)
   START view_afd -> afdeling_hstage                         executed in 0.000 seconds (6.632 seconds since start)
Traceback (most recent call last):
  File "/opt/dwh2/PYELT/pyelt/process/etl.py", line 187, in source_to_sor_by_hash
    file_name = mappings.source.to_csv(md5_only=True, filter=mappings.filter, ignore_fields=mappings.ignore_fields, debug=debug)
  File "/opt/dwh2/PYELT/pyelt/sources/databases.py", line 110, in to_csv
    with open(file_name, 'w', newline='', encoding='utf8') as fp:
PermissionError: [Errno 13] Permission denied: '/tmp/pyelt/datatransfer/NLHP/view_afd_hash.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dwh2/main.py", line 9, in <module>
    main_clinics_pipeline_run()
  File "/opt/dwh2/CLINICAL_DATAVAULT_CLINICS/pipelines/clinics_main_process.py", line 58, in main_clinics_pipeline_run
    pipeline.run()
  File "/opt/dwh2/PYELT/pyelt/pipeline.py", line 167, in run
    pipe.run(parts)
  File "/opt/dwh2/PYELT/pyelt/pipeline.py", line 584, in run
    etl.source_to_sor(mapping)
  File "/opt/dwh2/PYELT/pyelt/process/etl.py", line 91, in source_to_sor
    self.source_to_sor_by_hash(mappings)
  File "/opt/dwh2/PYELT/pyelt/process/etl.py", line 303, in source_to_sor_by_hash
    self.logger.log_error(mappings.name, err_msg=ex.args[0])
  File "/opt/dwh2/PYELT/pyelt/helpers/pyelt_logging.py", line 135, in log_error
    while err_msg.endswith('\n'):
AttributeError: 'int' object has no attribute 'endswith'

**Comment by jvlith** [comment]
# 

ERROR tijdens : view_afspraak_deelnemer -> afspraak_deelnemer_hstage

SQL:

# ERROR: sequence item 2: expected str instance, NoneType found

**Comment by hvanreenen** [comment]
oude issue treedt niet meer op
